### ISSUE TITLE
No TOS, No Privacy Policy, No Evidence of Trustworthiness

### ISSUE THREAD

**Issue by mlissner** [oldarmyc/pitchfork#65]
I was just told by Rackspace support to use this website. I get that that's probably not an issue with this site exactly, but I want to flag the many issues I had with this advice. Some of these may be real and others perceived, but I'm really shocked that Rackspace support told me to give my API key to a website.

Some issues:

 - This website wants my API key, which controls all of my servers. Rackspace support should NEVER, ever tell people to give their API key to a third party.

 - There's no privacy policy, and anyway, the privacy policy isn't Rackspace's privacy policy.

 - There are no terms of service. Say something goes wrong as a result of a bug in this software and it damages a server I have. I can't restore for some reason and my business collapses. Are *you* ready for that lawsuit?

 - There's no contact info. That's not good. The footer says the site is maintained by a Rackspace employee. Who? 

I think the fix to these issues is fairly simple: Just don't ask for API information and don't do anything on the user's behalf. Basically, make the site into an interactive API documentation and that's it.

PS: Sorry to be a wet blanket. But ultimately, some things shouldn't exist because of the security concerns that they create. If these API calls are indeed needed by the Rackspace community, then Rackspace should build them into the UI or make a website like this that it owns and operates itself.

**Comment by oldarmyc** [comment]
The application is licensed under the Apache license and you can see the details of that license at the following location: http://www.apache.org/licenses/LICENSE-2.0
The License is also provided in the source code, but I went ahead and added a link to the license on the page so anyone can get it quickly.

The site is designed to help users browse and use the API for Rackspace products. There is no requirement that states you have to use the site, or that you have to login to the site to use it. You are free to browse all calls without logging into the application in order to see how the calls are structured, get documentation about the call, or to see any additional details needed to make the call.

You also have the option of checking out the code and running the site locally if you prefer. The README provides instructions on how to do it, and a link to the API calls so that you can load them into your own running application. Again the goal is to provide a way for users to be able to consume the APIs easily, while providing a reference and documentation to all calls that Rackspace provides. Whether that is through the site I provided or through a running local instance that you stand up is your choice.

The login does an authentication request to the API to retrieve a token. The authentication request does not store or save any details about the API key or the data object that is passed when making the call. The token that is retrieved in the authentication response is saved into a session variable while on the website, and once you log out or when the token expires that information is removed.

Contact is easily done through github as you were able to raise an issue that I was able to see, and easily respond in a way that documents the response.

**Comment by mlissner** [comment]
So, I get that you don't want to make the changes I'm suggesting here, but it doesn't really feel like you understood my concerns, so I'll make a few responses.

> The application is licensed under the Apache license and you can see the details of that license at the following location: http://www.apache.org/licenses/LICENSE-2.0
The License is also provided in the source code, but I went ahead and added a link to the license on the page so anyone can get it quickly.

I'm really not concerned at all about the license, and it wasn't something that I brought up. I'm talking about the *Terms of Service* and *Privacy Policy* for the site. I'm a big open source advocate, so yay for Apache License, but where do you say how you use my data and my tokens? Where do you say how legal disputes are handled? Where do you CYA in case you ruin somebody's machine? You should consider looking into Terms of Service and why they're important, for your own sake. You're leaving yourself wide open without them. 

I'm not a lawyer, and I mentioned this before, but you'll be in legal hot water if you ruin somebody's server through a bug in your software. Do you want that? Get some terms of service and write a privacy policy -- at a minimum.

> The site is designed to help users browse and use the API for Rackspace products. There is no requirement that states you have to use the site, or that you have to login to the site to use it.

That's true. But, the Rackspace documentation [does][1] [recommend][2] using the site, and the phone help I received directly from Rackspace recommended I use the site. This is crazy:

 - Rackspace is a company that houses thousands of servers and all the data on them, including credit card data, social security numbers and corporate data.
 - Rackspace is recommending that I give my API key to a third party website they don't control so that that website can do things on my behalf. 

I can't reiterate how insane this is. You work for Rackspace, so I was hoping you'd consider how to make this situation better.

> You also have the option of checking out the code and running the site locally if you prefer. The README provides instructions on how to do it, and a link to the API calls so that you can load them into your own running application. Again the goal is to provide a way for users to be able to consume the APIs easily, while providing a reference and documentation to all calls that Rackspace provides. Whether that is through the site I provided or through a running local instance that you stand up is your choice.

Totally, and that's great. That's the *only* way that you should give a website your API key for Rackspace -- when you're the one running the website. Friction is real though, and I'd bet that you see a lot more activity on your front end than you do on Github. Here I have to point out that just because people find something to be useful doesn't mean it should exist. 

Maybe a good solution is a configuration option that turns the login functionality on or off. Then, in your hosted version you turn it off, but in the self-hosted version, people can turn it on.

> The login does an authentication request to the API to retrieve a token. The authentication request does not store or save any details about the API key or the data object that is passed when making the call. The token that is retrieved in the authentication response is saved into a session variable while on the website, and once you log out or when the token expires that information is removed.

So you say, and I believe you, but I have absolutely no way to know what code is actually on your server. Once I give you my API key, you could keep it, you could make your own, you could add users to my servers, you could DO ANYTHING. How do I know that the website that I see online is the same one that's in Github? They could be the same. Or not. Say I have 40 tokens in my system. Would I notice if you created one more for your own bitcoin-mining use? Maybe. Maybe not.

How do I know your server is updated regularly and hasn't been hacked? How do *you* know? You do realize you've got a big target on your back, right?

> Contact is easily done through github as you were able to raise an issue that I was able to see, and easily respond in a way that documents the response.

Sort of, but the core of the issue is that this website is run by you, not by Rackspace. When I send in a support request, I don't want to do it via github. I want to do it via Rackspace. When you have a bug that breaks my system, I want Rackspace support, not you. Etc. 

I'll stop here, but I hope you're seeing my perspective. If I were Rackspace, I would *shut this down*, not support it. There's just too much risk and too little accountability. Don't get me wrong, it's a great idea and a great execution, but unless it's run by Rackspace or another accountable organization, it probably shouldn't exist in its current form.


[1]: https://community.rackspace.com/products/f/25/t/6432
[2]: https://community.rackspace.com/products/f/25/t/7186
