### ISSUE TITLE
Allow for multiple networks in the update launch configuration GUI

### ISSUE THREAD

**Issue by jakubkrajcovic** [oldarmyc/pitchfork#9]
The update launch configuration GUI also does not allow for specifying more than one network, despite the fact that the autoscale API does support multiple networks. Our customers often need to specify a private network when using autoscaling, often for back-end traffic between application servers in an AS group.

Would it be possible to modify the pitchfork GUI in a way such that it would allow the input of multiple networks in the update launch configuration API call?

thanks
j

![screen shot 2014-09-03 at 10 35 57](https://cloud.githubusercontent.com/assets/3772438/4128045/b13982e4-3303-11e4-9ea6-be39c230b482.png)

**Comment by oldarmyc** [comment]
This following has been added in PR #62 This affects the following calls, and has been deployed to production.

Autoscale - Create Group config
Autoscale - Replace Launch Config
Autoscale - Replace Launch Config (BFV)
Servers - Create Server
Servers - Create Server (BFV)

This does not solve groups of fields i.e. metadata, but I am looking into it to see what can be done to complete it. Will reopen Issue #8 as it is pertaining to a group of fields instead of a single field.
